#!/bin/bash
# Debug bash scripts which call other bash scripts.
# Usage:
#   BASH_ENV=.../bash_env_debug ./my-script [args...]

echo >&2 ".<[BASH_ENV=$BASH_ENV]>."
# include host name, script name, line number, function name
# better bash debugging
# FUNCNAME dash prevents errors for set -u aka set -o nounset
PS4='+\h:${BASH_SOURCE}(${FUNCNAME[0]-}):${LINENO}: '
# enable xtrace
set -x
