#!/bin/bash
# Usage:
# $0 USER@HOST [-r cookbook::recipe] .../COOKBOOK[.tgz]...
# $0 USER@HOST -j .../attribs.json   .../COOKBOOK[.tgz]...

set -eu
PROGRAM_DIR="${0%/*}"

TARGET=$1
shift

QRECIPE=
if [ "$1" = -r ]; then
    # recipe qualified with cookbook::
    QRECIPE="$2"
    shift 2
fi
JSON_ATTRIBS=
if [ "$1" = -j ]; then
    # attributes including the run list
    JSON_ATTRIBS="$2"
    shift 2
fi

# $@ is cookbooks

printf -v QUOTED_FILES "%q " \
    "${PROGRAM_DIR}"/install-chef-solo-apply-cookbook.sh "${PROGRAM_DIR}"/install-chef/ "${PROGRAM_DIR}"/run-chef-solo/ $JSON_ATTRIBS "$@"
printf -v QUOTED_COMMAND "%q " \
    sh "${PROGRAM_DIR/#\//}"/install-chef-solo-apply-cookbook.sh \
        ${QRECIPE:+-r} $QRECIPE \
        ${JSON_ATTRIBS:+-j} ${JSON_ATTRIBS/#\//} \
        "${@/#\//}" # remove leading / like tar does
"${PROGRAM_DIR}"/deploy.sh "$TARGET" "$QUOTED_FILES" "$QUOTED_COMMAND"
