#!/bin/bash
# Usage:
# $0 USER@HOST [-r cookbook::recipe] .../COOKBOOK[.tgz]...

set -eu
TARGET=$1
shift

QRECIPE=
if [ "$1" = -r ]; then
    # recipe qualified with cookbook::
    QRECIPE="$2"
    shift 2
fi

# $@ is cookbooks

printf -v QUOTED_FILES "%q " \
    install-chef-solo-apply-cookbook.sh install-chef/ run-chef-solo/ "$@"
printf -v QUOTED_COMMAND "%q " \
    sh ./install-chef-solo-apply-cookbook.sh ${QRECIPE:+-r} $QRECIPE "${@/#\//}" # remove leading / like tar does
./deploy.sh "$TARGET" "$QUOTED_FILES" "$QUOTED_COMMAND"
