#!/bin/bash
# $0 [-r cookbook::recipe] .../cookbook[.tgz]...
set -e
set -u
PROGRAM_DIR=`dirname $0`

if [ "$1" = -r ]; then
    # recipe qualified with cookbook::
    QRECIPE="$2"
    shift 2
fi
JSON_ATTRIBS=
if [ "$1" = -j ]; then
    # attributes including the run list
    JSON_ATTRIBS="$2"
    shift 2
fi

mkdir -p cookbooks

for COOKBOOK; do # in "$@"
    CBNAME=${COOKBOOK##*/}

    mv "$COOKBOOK" cookbooks
    case "$CBNAME" in
        *.tgz)
            tar -f cookbooks/$CBNAME -C cookbooks -xv
            CBNAME=${CBNAME%.tgz}
    esac
    : ${FIRST_CBNAME=$CBNAME}
done

: ${QRECIPE=$FIRST_CBNAME::default}
SOLO_RB="${PROGRAM_DIR}"/solo.rb
if [ -z "$JSON_ATTRIBS" ]; then
    JSON_ATTRIBS="${PROGRAM_DIR}"/solo.json
    cat >$JSON_ATTRIBS <<EOF
{
    "run_list": [ "recipe[$QRECIPE]" ]
}
EOF
fi
sudo chef-solo -c $SOLO_RB -j $JSON_ATTRIBS
