#!/bin/bash
# $0 [-r cookbook::recipe] .../cookbook[.tgz]...
set -x
set -e
set -u

if [ "$1" = -r ]; then
    # recipe qualified with cookbook::
    QRECIPE="$2"
    shift 2
fi

mkdir -p cookbooks

for COOKBOOK; do # in "$@"
    CBNAME=${COOKBOOK##*/}

    mv "$COOKBOOK" cookbooks
    case "$CBNAME" in
        *.tgz)
            tar -f cookbooks/$CBNAME -C cookbooks -xv
            CBNAME=${CBNAME%.tgz}
    esac
    : ${FIRST_CBNAME=$CBNAME}
done

: ${QRECIPE=$FIRST_CBNAME::default}
SOLO_RB=run-chef-solo/solo.rb
SOLO_JSON=run-chef-solo/solo.json
cat >$SOLO_JSON <<EOF
{
    "run_list": [ "recipe[$QRECIPE]" ]
}
EOF
sudo chef-solo -c $SOLO_RB -j $SOLO_JSON
