#!/bin/bash
set -x
set -e

PROGRAM_DIR="${0%/*}"
if test -f /etc/SuSE-release; then
    "${PROGRAM_DIR}"/opensuse
elif grep DISTRIB_ID=Ubuntu /etc/*-release; then
    "${PROGRAM_DIR}"/ubuntu
else
    echo Unknown distro, fix me.
    false
fi
