#!/bin/bash
set -e

reponame() {
    release=$(cat /etc/SuSE-release)
    case "$release" in
        *openSUSE?11.4*)
            echo openSUSE_11.4 ;;
        *openSUSE?12.1*)
            echo openSUSE_12.1 ;;
        *openSUSE?12.2*)
            echo openSUSE_12.2 ;;
        *"SUSE Linux Enterprise Server"*"VERSION = 11"*"PATCHLEVEL = 1"*)
            echo SLE_11_SP1 ;;
        *"SUSE Linux Enterprise Server"*"VERSION = 11"*"PATCHLEVEL = 2"*)
            echo SLE_11_SP2 ;;
    esac
}

addrepo() {
    REPO=systemsmanagement:chef:master
    REPOPATH=${REPO//:/:/}  # turn a:b:c into a:/b:/c
    zypper addrepo http://download.opensuse.org/repositories/${REPOPATH}/$(reponame) ${REPO}
    zypper --gpg-auto-import-keys refresh ${REPO}
}

install() {
    zypper --non-interactive install rubygem-chef
}

rpm -q rubygem-chef && exit

install && exit

addrepo
install
